-- Seed products from existing Products.ts file
-- This migration inserts all existing products into the database

-- Insert products
INSERT INTO products (
  name, 
  slug, 
  short_description, 
  long_description, 
  price, 
  main_image, 
  category, 
  product_group, 
  is_featured,
  usage_instructions,
  ingredients,
  weight_options,
  stock_quantity,
  is_available,
  certifications,
  tags
) VALUES
  -- OLEJE
  (
    'Olej Lniany BIO',
    'olej-lniany-bio',
    '250 ml · tłoczony na zimno',
    'Nasz olej lniany to esencja zdrowia zamknięta w ciemnym szkle. Tłoczony metodą ''na zimno'' w temperaturze nieprzekraczającej 38°C. Bogaty w kwasy Omega-3.',
    29.90,
    '/Img/Olejbio.png',
    'olej-lniany',
    'oleje',
    true,
    'Spożywać na zimno. Doskonały do sałatek, kasz, twarogu (pasta Budwigowa).',
    '100% olej z nasion lnu brązowego.',
    '[{"size": "250 ml", "price": 29.90}, {"size": "500 ml", "price": 49.90}, {"size": "1000 ml", "price": 89.90}]'::jsonb,
    100,
    true,
    ARRAY['BIO', 'Ekologiczne'],
    ARRAY['bio', 'omega-3', 'tłoczony na zimno']
  ),
  (
    'Olej z Czarnuszki',
    'olej-z-czarnuszki',
    '100 ml · złoto faraonów',
    'Intensywny w smaku olej z czarnuszki egipskiej. Znany ze swoich właściwości wspierających odporność i układ trawienny.',
    45.00,
    '/Img/Olejbio.png',
    'olej-czarnuszka',
    'oleje',
    true,
    '1 łyżeczka dziennie na czczo lub jako dodatek do potraw.',
    '100% olej z czarnuszki egipskiej.',
    '[{"size": "100 ml", "price": 45.00}, {"size": "250 ml", "price": 99.00}, {"size": "500 ml", "price": 179.00}]'::jsonb,
    50,
    true,
    ARRAY['Naturalne'],
    ARRAY['odporność', 'czarnuszka', 'egipska']
  ),
  (
    'Olej Kokosowy',
    'olej-kokosowy',
    '500 ml · nierafinowany',
    'Nierafinowany olej kokosowy o subtelnym zapachu świeżego kokosa. Idealny do kuchni i pielęgnacji.',
    39.90,
    '/Img/Olejkokosowy.png',
    'olej-kokosowy',
    'oleje',
    false,
    'Do smażenia, pieczenia i pielęgnacji skóry.',
    '100% olej kokosowy nierafinowany.',
    '[{"size": "300 ml", "price": 29.90}, {"size": "500 ml", "price": 39.90}, {"size": "900 ml", "price": 69.90}]'::jsonb,
    80,
    true,
    ARRAY['Naturalne'],
    ARRAY['kokos', 'nierafinowany', 'wegańskie']
  ),
  (
    'Oliwa z Oliwek Extra Virgin',
    'oliwa-z-oliwek-extra-virgin',
    '500 ml · Hiszpania',
    'Najwyższej klasy oliwa z pierwszego tłoczenia. Niska kwasowość, głęboki smak.',
    59.00,
    '/Img/Olejbio.png',
    'oliwa',
    'oleje',
    false,
    'Idealna do sałatek i potraw na zimno.',
    '100% oliwa z oliwek extra virgin.',
    '[{"size": "500 ml", "price": 59.00}, {"size": "1000 ml", "price": 109.00}]'::jsonb,
    60,
    true,
    ARRAY['Extra Virgin'],
    ARRAY['oliwa', 'hiszpania', 'premium']
  ),
  (
    'Olej z Ostropestu',
    'olej-z-ostropestu',
    '250 ml · wsparcie wątroby',
    'Olej tłoczony z nasion ostropestu plamistego. Naturalne źródło sylimaryny.',
    35.00,
    '/Img/Olejbio.png',
    'olej-inne',
    'oleje',
    false,
    'Spożywać 1-2 łyżeczki dziennie.',
    '100% olej z ostropestu plamistego.',
    '[{"size": "250 ml", "price": 35.00}, {"size": "500 ml", "price": 65.00}]'::jsonb,
    40,
    true,
    ARRAY['Naturalne'],
    ARRAY['ostropest', 'wątroba', 'sylimaryna']
  ),

  -- ZIARNA
  (
    'Pestki Dyni',
    'pestki-dyni',
    '200 g · polska uprawa',
    'Pestki dyni z polskiej uprawy. Bogate w cynk i magnez.',
    19.90,
    '/Img/Dynia.png',
    'ziarna-dynia',
    'ziarna',
    false,
    'Idealne jako przekąska lub dodatek do sałatek.',
    '100% pestki dyni.',
    '[{"size": "200 g", "price": 19.90}, {"size": "500 g", "price": 45.00}, {"size": "1 kg", "price": 85.00}]'::jsonb,
    120,
    true,
    ARRAY['Polska uprawa'],
    ARRAY['dynia', 'cynk', 'magnez']
  ),
  (
    'Nasiona Chia',
    'nasiona-chia',
    '250 g · superfood',
    'Nasiona chia bogate w omega-3, błonnik i białko.',
    15.90,
    '/Img/Dynia.png',
    'ziarna-inne',
    'ziarna',
    false,
    'Dodawaj do jogurtów, koktajli lub wypieków.',
    '100% nasiona chia.',
    '[{"size": "250 g", "price": 15.90}, {"size": "500 g", "price": 29.90}]'::jsonb,
    150,
    true,
    ARRAY['Superfood'],
    ARRAY['chia', 'omega-3', 'błonnik']
  ),
  (
    'Słonecznik Łuskany',
    'slonecznik-luskany',
    '500 g · chrupiący',
    'Łuskany słonecznik o chrupiącej konsystencji.',
    12.00,
    '/Img/Dynia.png',
    'ziarna-slonecznik',
    'ziarna',
    false,
    'Przekąska lub dodatek do wypieków.',
    '100% słonecznik łuskany.',
    '[{"size": "500 g", "price": 12.00}, {"size": "1 kg", "price": 22.00}]'::jsonb,
    200,
    true,
    ARRAY['Naturalne'],
    ARRAY['słonecznik', 'przekąska']
  ),

  -- ORZECHY
  (
    'Migdały',
    'migdaly',
    '200 g · niesolone',
    'Migdały niesolone, naturalne. Bogate w witaminę E.',
    24.90,
    '/Img/Migdały.png',
    'orzechy-migdaly',
    'orzechy',
    false,
    'Przekąska lub składnik wypieków.',
    '100% migdały.',
    '[{"size": "200 g", "price": 24.90}, {"size": "500 g", "price": 59.00}, {"size": "1 kg", "price": 110.00}]'::jsonb,
    90,
    true,
    ARRAY['Naturalne'],
    ARRAY['migdały', 'witamina E', 'niesolone']
  ),
  (
    'Orzechy Włoskie',
    'orzechy-wloskie',
    '200 g · połówki',
    'Orzechy włoskie w połówkach. Bogate w omega-3.',
    29.90,
    '/Img/Migdały.png',
    'orzechy-wloskie',
    'orzechy',
    false,
    'Przekąska lub dodatek do ciast.',
    '100% orzechy włoskie.',
    '[{"size": "200 g", "price": 29.90}, {"size": "500 g", "price": 69.00}]'::jsonb,
    70,
    true,
    ARRAY['Naturalne'],
    ARRAY['orzechy włoskie', 'omega-3']
  ),
  (
    'Nerkowce',
    'nerkowce',
    '200 g · maślane',
    'Nerkowce o maślanym smaku. Premium quality.',
    32.00,
    '/Img/Migdały.png',
    'orzechy-nerkowce',
    'orzechy',
    false,
    'Przekąska lub składnik potraw azjatyckich.',
    '100% nerkowce.',
    '[{"size": "200 g", "price": 32.00}, {"size": "500 g", "price": 75.00}]'::jsonb,
    60,
    true,
    ARRAY['Premium'],
    ARRAY['nerkowce', 'maślane', 'premium']
  ),

  -- KIEŁKI
  (
    'Nasiona na Kiełki: Rzodkiewka',
    'nasiona-kielki-rzodkiewka',
    '50 g · ostry smak',
    'Ekologiczne nasiona rzodkiewki do kiełkowania. Kiełki rzodkiewki są bogate w witaminę C i mają wyrazisty, pikantny smak. Idealne do kanapek.',
    4.90,
    '/Img/Dynia.png',
    'nasiona-kielki',
    'kielki',
    false,
    'Moczyć nasiona 4-6h, płukać 2 razy dziennie. Gotowe w 4-5 dni.',
    '100% nasiona rzodkiewki ekologiczne.',
    '[{"size": "50 g", "price": 4.90}]'::jsonb,
    100,
    true,
    ARRAY['Ekologiczne'],
    ARRAY['kiełki', 'rzodkiewka', 'witamina C']
  ),
  (
    'Nasiona na Kiełki: Brokuł',
    'nasiona-kielki-brokul',
    '50 g · sulforafan',
    'Kiełki brokuła to najbogatsze naturalne źródło sulforafanu - silnego przeciwutleniacza. Łagodne w smaku.',
    6.90,
    '/Img/Dynia.png',
    'nasiona-kielki',
    'kielki',
    false,
    'Moczyć nasiona 4-6h, płukać 2 razy dziennie. Gotowe w 4-6 dni.',
    '100% nasiona brokuła ekologiczne.',
    '[{"size": "50 g", "price": 6.90}]'::jsonb,
    80,
    true,
    ARRAY['Ekologiczne'],
    ARRAY['kiełki', 'brokuł', 'sulforafan']
  ),
  (
    'Nasiona na Kiełki: Lucerna',
    'nasiona-kielki-lucerna',
    '50 g · delikatne',
    'Kiełki lucerny (Alfalfa) są niezwykle delikatne i chrupiące. Zawierają fitestrogeny i witaminy z grupy B.',
    5.50,
    '/Img/Dynia.png',
    'nasiona-kielki',
    'kielki',
    false,
    'Moczyć nasiona 4-6h, płukać 2 razy dziennie. Gotowe w 5-7 dni.',
    '100% nasiona lucerny ekologiczne.',
    '[{"size": "50 g", "price": 5.50}]'::jsonb,
    90,
    true,
    ARRAY['Ekologiczne'],
    ARRAY['kiełki', 'lucerna', 'alfalfa']
  ),
  (
    'Kiełkownica Słoikowa',
    'kielkownica-sloikowa',
    'Zestaw Startowy',
    'Wygodny słoik ze specjalną nakrętką z sitkiem, który ułatwia codzienne płukanie kiełków. Najprostszy sposób na domową uprawę.',
    39.00,
    '/Img/Dynia.png',
    'akcesoria',
    'kielki',
    false,
    'Umieść nasiona w słoiku, przykryj sitkiem, płucz 2 razy dziennie.',
    'Słoik szklany 1L + nakrętka z sitkiem ze stali nierdzewnej.',
    '[{"size": "1 szt", "price": 39.00}]'::jsonb,
    30,
    true,
    NULL,
    ARRAY['kiełkownica', 'akcesoria', 'zestaw']
  ),

  -- MĄKI
  (
    'Mąka Kokosowa BIO',
    'maka-kokosowa-bio',
    '500 g · bezglutenowa',
    'Mąka powstająca z miąższu kokosa. Bogata w błonnik i białko, o niskiej zawartości węglowodanów. Idealna do wypieków keto i low-carb.',
    12.90,
    '/Img/Olejkokosowy.png',
    'maki-kokosowa',
    'maki',
    false,
    'Chłonie dużo wilgoci - używaj mniej niż zwykłej mąki w przepisach.',
    '100% mąka kokosowa.',
    '[{"size": "500 g", "price": 12.90}, {"size": "1 kg", "price": 23.90}]'::jsonb,
    70,
    true,
    ARRAY['BIO', 'Bezglutenowe'],
    ARRAY['mąka', 'kokos', 'keto', 'bezglutenowe']
  ),
  (
    'Mąka Migdałowa',
    'maka-migdalowa',
    '500 g · z blanszowanych migdałów',
    'Delikatna mąka ze zmielonych migdałów bez skórki. Baza do makaroników oraz ciast niskowęglowodanowych.',
    34.90,
    '/Img/Migdały.png',
    'maki-migdalowa',
    'maki',
    false,
    'Idealna do wypieków keto, makaroników i ciast.',
    '100% mąka migdałowa z blanszowanych migdałów.',
    '[{"size": "500 g", "price": 34.90}, {"size": "1 kg", "price": 65.00}]'::jsonb,
    50,
    true,
    ARRAY['Bezglutenowe'],
    ARRAY['mąka', 'migdały', 'keto', 'bezglutenowe']
  ),

  -- DODATKI
  (
    'Syrop z Agawy BIO',
    'syrop-z-agawy-bio',
    '400 ml · wegański miód',
    'Ekologiczny syrop z agawy to doskonała alternatywa dla cukru i miodu. Ma niski indeks glikemiczny i łatwo rozpuszcza się w zimnych napojach.',
    24.90,
    '/Img/Olejbio.png',
    'slodziki',
    'dodatki',
    false,
    'Używaj jako zamiennik cukru lub miodu.',
    '100% syrop z agawy ekologiczny.',
    '[{"size": "250 ml", "price": 19.90}, {"size": "400 ml", "price": 24.90}, {"size": "1 L", "price": 54.90}]'::jsonb,
    60,
    true,
    ARRAY['BIO', 'Wegańskie'],
    ARRAY['syrop', 'agawa', 'słodzik', 'wegańskie']
  ),
  (
    'Sos Sojowy Kikkoman',
    'sos-sojowy-kikkoman',
    '150 ml · naturalnie warzony',
    'Legendarny, naturalnie warzony sos sojowy. Składa się tylko z 4 składników: soi, pszenicy, wody i soli. Bez konserwantów.',
    14.90,
    '/Img/Olejbio.png',
    'sosy',
    'dodatki',
    false,
    'Dodatek do potraw azjatyckich, marynat i sosów.',
    'Soja, pszenica, woda, sól.',
    '[{"size": "150 ml", "price": 14.90}, {"size": "500 ml", "price": 39.90}, {"size": "1 L", "price": 69.90}]'::jsonb,
    100,
    true,
    ARRAY['Naturalne'],
    ARRAY['sos sojowy', 'kikkoman', 'azjatyckie']
  ),
  (
    'Erytrytol',
    'erytrytol',
    '500 g · 0 kcal',
    'Naturalna substancja słodząca bez kalorii. Nie podnosi poziomu cukru we krwi. Idealny dla diabetyków i osób na diecie ketogenicznej.',
    19.90,
    '/Img/Dynia.png',
    'slodziki',
    'dodatki',
    false,
    'Używaj jako zamiennik cukru w proporcji 1:1.',
    '100% erytrytol.',
    '[{"size": "500 g", "price": 19.90}, {"size": "1 kg", "price": 35.00}]'::jsonb,
    80,
    true,
    ARRAY['Naturalne'],
    ARRAY['erytrytol', 'słodzik', 'keto', '0 kcal']
  ),
  (
    'Sól Himalajska Różowa',
    'sol-himalajska-rozowa',
    '500 g · drobna',
    'Nieoczyszczona sól krystaliczna bogata w minerały. Wydobywana tradycyjnymi metodami u podnóża Himalajów.',
    5.90,
    '/Img/Dynia.png',
    'przyprawy',
    'dodatki',
    false,
    'Używaj jak zwykłej soli kuchennej.',
    '100% sól himalajska różowa.',
    '[{"size": "500 g", "price": 5.90}, {"size": "1 kg", "price": 10.90}]'::jsonb,
    150,
    true,
    ARRAY['Naturalne'],
    ARRAY['sól', 'himalajska', 'minerały']
  ),

  -- ZESTAWY
  (
    'Zestaw Odporność',
    'zestaw-odpornosc',
    'Czarnuszka + Olej Lniany',
    'Zestaw wspierający odporność: Olej z czarnuszki 100ml + Olej lniany BIO 250ml. Idealne połączenie na zimę.',
    69.00,
    '/Img/Olejbio.png',
    'zestawy',
    'zestawy',
    true,
    'Spożywaj olej z czarnuszki na czczo, olej lniany dodawaj do posiłków.',
    'Olej z czarnuszki 100ml + Olej lniany BIO 250ml.',
    '[{"size": "Zestaw", "price": 69.00}]'::jsonb,
    30,
    true,
    ARRAY['Zestaw'],
    ARRAY['zestaw', 'odporność', 'prezent']
  )
ON CONFLICT (slug) DO NOTHING;

-- Update sequence to start from correct number
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));
